export interface ColorScheme {
  background: string;
  surface: string;
  surfaceSecondary: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  border: string;
  borderLight: string;
  shadow: string;
  card: string;
  input: string;
  placeholder: string;
  error: string;
  success: string;
  warning: string;
  info: string;
  primary: string;
  primaryLight: string;
  accent: string;
  overlay: string;
  codeBackground: string;
  selectedBackground: string;
  selectedBackgroundMac: string;
  inputBackground: string;
  labelBackground: string;
  messageBackground: string;
  reasoningBackground: string;
  inputBorder: string;
  drawerBackground: string;
  drawerBackgroundMac: string;
  promptButtonBackground: string;
  promptButtonBorder: string;
  promptText: string;
  promptSelectedBorder: string;
  promptAddButtonBackground: string;
  promptAddButtonBorder: string;
  promptAddText: string;
  promptDeleteBackground: string;
  promptDeleteText: string;
  promptScreenInputBorder: string;
  promptScreenSaveButton: string;
  promptScreenSaveButtonText: string;
  textDarkGray: string;
  inputToolbarBorder: string;
  fileListBackground: string;
  fileItemBorder: string;
  addButtonBackground: string;
  chatScreenSplit: string;
}

export const lightColors: ColorScheme = {
  background: '#ffffff',
  surface: '#f5f5f5',
  surfaceSecondary: '#f9f9f9',
  text: '#000000',
  textSecondary: '#666666',
  textTertiary: '#999999',
  border: '#e0e0e0',
  borderLight: '#eaeaea',
  shadow: 'rgba(0,0,0,0.1)',
  card: '#ffffff',
  input: '#f8f8f8',
  placeholder: '#999999',
  error: '#ff4444',
  success: '#00C851',
  warning: '#ffbb33',
  info: '#33b5e5',
  primary: '#007AFF',
  primaryLight: '#E3F2FD',
  accent: '#FF6B6B',
  overlay: 'rgba(0,0,0,0.5)',
  codeBackground: '#F8F8F8',
  selectedBackground: '#F5F5F5',
  selectedBackgroundMac: '#ECECEC',
  inputBackground: '#ffffff',
  labelBackground: '#ffffff',
  messageBackground: '#f2f2f2',
  reasoningBackground: '#f3f3f3',
  inputBorder: '#808080',
  drawerBackground: 'transparent',
  drawerBackgroundMac: '#F9F9F9',
  promptButtonBackground: '#E8E8E8',
  promptButtonBorder: '#E8E8E8',
  promptText: '#333333',
  promptSelectedBorder: '#000000',
  promptAddButtonBackground: '#ffffff',
  promptAddButtonBorder: '#666666',
  promptAddText: '#666666',
  promptDeleteBackground: '#666666',
  promptDeleteText: '#ffffff',
  promptScreenInputBorder: '#e0e0e0',
  promptScreenSaveButton: '#007AFF',
  promptScreenSaveButtonText: '#ffffff',
  textDarkGray: '#333333',
  inputToolbarBorder: '#000000',
  fileListBackground: '#ffffff',
  fileItemBorder: '#e0e0e0',
  addButtonBackground: '#f0f0f0',
  chatScreenSplit: '#c7c7c7',
};

export const darkColors: ColorScheme = {
  background: '#000000',
  surface: '#1a1a1a',
  surfaceSecondary: '#2a2a2a',
  text: '#ffffff',
  textSecondary: '#cccccc',
  textTertiary: '#888888',
  border: '#333333',
  borderLight: '#444444',
  shadow: 'rgba(255,255,255,0.1)',
  card: '#1a1a1a',
  input: '#2a2a2a',
  placeholder: '#888888',
  error: '#ff6b6b',
  success: '#51cf66',
  warning: '#ffd43b',
  info: '#74c0fc',
  primary: '#0099ff',
  primaryLight: '#1a1a2e',
  accent: '#ff7979',
  overlay: 'rgba(0,0,0,0.8)',
  codeBackground: '#1a1a1a',
  selectedBackground: '#2a2a2a',
  selectedBackgroundMac: '#333333',
  inputBackground: '#000000',
  labelBackground: '#000000',
  messageBackground: '#2a2a2a',
  reasoningBackground: '#2a2a2a',
  inputBorder: '#555555',
  drawerBackground: '#000000',
  drawerBackgroundMac: '#000000',
  promptButtonBackground: '#333333',
  promptButtonBorder: '#333333',
  promptText: '#cccccc',
  promptSelectedBorder: '#cccccc',
  promptAddButtonBackground: '#2a2a2a',
  promptAddButtonBorder: '#cccccc',
  promptAddText: '#cccccc',
  promptDeleteBackground: '#888888',
  promptDeleteText: '#ffffff',
  promptScreenInputBorder: '#444444',
  promptScreenSaveButton: '#0099ff',
  promptScreenSaveButtonText: '#ffffff',
  textDarkGray: '#cccccc',
  inputToolbarBorder: '#cccccc',
  fileListBackground: '#000000',
  fileItemBorder: '#cccccc',
  addButtonBackground: '#333333',
  chatScreenSplit: '#404040',
};
